In [2]:
import tensorflow as tf

tf.constant: This function creates a tensor that holds constant values. You pass it a value, like a number or a list, and TensorFlow makes it into a tensor.

In [6]:
# creating tensors 
scalar = tf.constant(5)
vector = tf.constant([1,2,3,4])
matrix = tf.constant([[1,2,4,5],[5,2,5,2]])
print(f"Scalar : {scalar}")
print(f"vector : {vector}")
print(f"matrix : {matrix}")

Scalar : 5
vector : [1 2 3 4]
matrix : [[1 2 4 5]
 [5 2 5 2]]


In [9]:
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(f"{matrix} + 10 = {tf.add(matrix,10)}")
matrix1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(f"{matrix} * {matrix1} = {tf.matmul(matrix,matrix1)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] + 10 = [[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1 2 3]
 [4 5 6]
 [7 8 9]] * [[1 2 3]
 [4 5 6]
 [7 8 9]] = [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
